name: Update CSV File

on:
  schedule:
    - cron: "*/10 * * * *"  # Запуск каждые 10 минут
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Полное клонирование для работы с pull

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install requests

    - name: Run update script
      run: python update_csv.py

    - name: Stash changes (if any)
      run: |
        git add .
        git stash || echo "No changes to stash"

    - name: Pull latest changes
      run: git pull --rebase origin main

    - name: Apply stashed changes (if any)
      run: git stash pop || echo "No stashed changes to apply"

    - name: Commit and push changes
      run: |
        git add data.csv
        git commit -m "Update CSV file" || echo "No changes to commit"
        git push origin main
